name: "Python CI"

env:
  GITLAB_PROJECT_ID: "12087"

on:
  push:
    branches:
    - develop
    - main
  pull_request:
    paths:
    - '**'                              # Include all files and directories in the repository by default.
    - '!.github/workflows/**'           # Exclude all workflow files
    - '.github/workflows/python-ci.yml' # except the current file.
    - '!.github/ISSUE_TEMPLATE/**'      # Exclude files and directories that don't impact tests or code like templates, metadata, and documentation.
    - '!.gitignore'
    - '!.asf.yml'
    - '!mkdocs/**'
    - '!.gitattributes'
    - '!README.md'
    - '!CONTRIBUTING.md'
    - '!LICENSE'
    - '!NOTICE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: make install-poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: poetry
        cache-dependency-path: ./poetry.lock
    - name: Install
      run: make install-dependencies
    - name: Linters
      run: make lint
    - name: Tests
      run: make test-coverage
    - name: Invoke GitLab CI/CD
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'develop')
      run: |
        curl -s -X POST -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            "https://gitlab.trading.imc.intra/api/v4/projects/${GITLAB_PROJECT_ID}/mirror/pull"
        sleep 30
        curl -s -X POST --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" --form "ref=develop" \
            "https://gitlab.trading.imc.intra/api/v4/projects/${GITLAB_PROJECT_ID}/trigger/pipeline"
